---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: copy nginx config file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx