- name: Initialize Kubernetes cluster
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_output

- name: Create Kubernetes config directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy kubeconfig to user directory
  shell: cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config && chown ubuntu:ubuntu /home/ubuntu/.kube/config

- name: Install Calico CNI networking
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Allow workloads to run on the master node (since it's single-node)
  shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
