---
nginx_user: www-data
nginx_error_log: /var/log/nginx/error.log
nginx_pidfile: /run/nginx.pid
nginx_worker_processes: auto
nginx_extra_conf_options: |

nginx_worker_connections: 1024
nginx_multi_accept: on
nginx_mime_file_path: /etc/nginx/mime.types
nginx_server_names_hash_bucket_size: 64
nginx_client_max_body_size: 16m
nginx_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
nginx_access_log: /var/log/nginx/access.log
nginx_sendfile: on
nginx_tcp_nopush: on
nginx_tcp_nodelay: on
nginx_keepalive_timeout: 65
nginx_keepalive_requests: 100
nginx_server_tokens: off
nginx_proxy_cache_path: ''
nginx_extra_http_options: |

nginx_upstreams: []
nginx_ssl_config: default
nginx_default_ssl_config: default
nginx_conf_path: /etc/nginx/conf.d
nginx_vhost_path: /etc/nginx/sites-enabled
