---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java 21
  ansible.builtin.apt:
    name: openjdk-21-jre
    state: present

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present